### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by ESK0** [ESFramework/es.lib#2]
Hey, how does custom icon works? I is not mentioned in your readme, but shown on example gif

**Comment by ESFramework** [comment]
Just put icon before text for now and usage of custom icon + promise system will coming soon

**Comment by ESK0** [comment]
Awesome... any ETA for this update?

**Comment by ESFramework** [comment]
i am working on it

**Comment by ESFramework** [comment]
> Awesome... any ETA for this update?

_Sorry for update delay._

Update to v1.2.1 for custom icon usage
